# Template configuration file for SuRE pipeline development.

# General parameters at the top of file. Required and consistently structured
#   parameters/SuRE input FASTQ files in the latter half.

############################
#### General Parameters ####
############################
# General parameters can be project specific and are not accounted
#   for to be strictly structured across all projects.
# The idea is that when creating a new pipeline, the general
#   parameters section is the only part of the config file you will
#   have to add/remove variables.

# Expected adapter sequence in cDNA/plDNA reads
ADPT_SEQ: "CCTAGCTAACTATAACGGTCCTAAGGTAGCGAA"
# Expected adapter sequence in forward iPCR reads
ADPTR_IPCR_FORW_SEQ: "CCTAGCTAACTATAACGGTCCTAAGGTAGCGAACCAGTGAT"
# Expected adapter sequence in reverse iPCR reads
ADPTR_IPCR_REV_SEQ: "CCAGTCGT"

# The restriction site motif used in previous versions of SuRE
#   methodology.
# No longer used (TODO remove this dependecy from the snakefile
#   scripts of standard sure pipeline.)
CUTMOTIF_NONE: &CUTMOTIF_NONE
  ""

# Path + prefix of reference sequence index files for bowtie2
BOWTIE2_REFSEQ: "/data/data/genomes/H_sapiens/hg38/bowtie2/hg38_no_alt"
# other examples for indices:
# /data/data/genomes/H_sapiens/hg38/bowtie2/hg38_no_alt
# /data/data/genomes/H_sapiens/hg38/bowtie2/hg38_no_alt_plus_hs38d1
# /data/data/genomes/S_lycopersicum/SL4.0/bowtie2-index/SL4.0

# Text file one per line of chromosome names and size in bp.
CHROMSIZES: "/data/data/genomes/H_sapiens/hg38/hg38.chromsizes"

# Bowtie2 setting which specifies the maximum length of DNA between start of
#   read 1 and start of read 2 before flagging paired reads as discordantly
#   aligned.
MAX_INSERT_LENGTH: 1000

# Specify which chromosomes will be included in the data processing
#   use this to run the pipeline on a limited (test) data set
CHR_TARGET:
  - chr1
  - chr2
  - chr3
  - chr21
  - chr22
  - chrX
  - chrY

# Select the processing to include SNPs or not
# ALLELE_SPECIFIC: "yes"
ALLELE_SPECIFIC: 0
# if ALLELE_SPECIFIC this folder will contain the SNP annotation (what format?)
SNP_DIR: "/DATA/home/ludo/projects/LP140430_SureSeq_JvArensbergen/data/LP170210_SuRE42-45_1000Genomes/"

# Genome ID. Can be arbritrary as was previously used for 1000
#   genome project IDs in Nat Gen paper? TODO Also check about
#   removing this dependency.
GID: "X22"


##########################################
#### REQUIRED: PARAMETERS/INPUT FILES ####
##########################################
# In order to maintain a modularized pipeline development system, some
#   parameters are required to be consistently structured/named across all
#   projects.


# Name of SuRE library to be processed.
LIBRARY: "SuRE_X_22"

# Root directory for all generated output.
OUTDIR: "SuRE-pipelineOutput"

#### INPUT iPCR, cDNA, plDNA FASTQs ####
########################################
# If there is no existing input for a specific category e.g no plDNA then it is
#   safe to leave the entries empty. Checks are performed within the snakefile
#   and processing adjusted based on value of samples dictionary for each
#   category of input.

# iPCR Section.
iPCR:
  # Path to directory containing iPCR FASTQ files.
  FASTQ_DIR:
    "/scratch/james/projects/JB210208_SuRE_CMV/raw_data_copy/SuRE_X22"
  # Path to sub-directory within 'OUTDIR' for iPCR related output.
  OUTDIR:
    "iPCR"
  # Name of samples (used to label data files and data columns) with a list of fastq filenames
  SAMPLES:
    SuRE_iPCR_X22_1:
      R1: SuRE_iPCR_X22_1_EKDL200012293-1a-3_HJV7LDSXY_L1_1.fq.gz
      R2: SuRE_iPCR_X22_1_EKDL200012293-1a-3_HJV7LDSXY_L1_2.fq.gz
    SuRE_iPCR_X22_2:
      R1: SuRE_iPCR_X22_2_EKDL200012293-1a-3_HJV7LDSXY_L1_1.fq.gz
      R2: SuRE_iPCR_X22_2_EKDL200012293-1a-3_HJV7LDSXY_L1_2.fq.gz

# cDNA Section.
cDNA:
  # Path to directory containing cDNA fastq files
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161219_SuRE23_reProc/fastq/cDNA/"
  # Path to sub-directory within 'OUTDIR' for cDNA related output
  OUTDIR:
    "cDNA"
  # Name of samples (used to label data files and data columns) with a list of fastq filenames
  SAMPLES:
    SuRE23_45_B1_T1:
      - 3520_1_12_1_RNA_45_5_K562_SuRE23_TFrep1_PCRrep1_pgcDNA_adapter_2_150604_hg_CAGATCA_L002_R1_001.fastq.gz
    SuRE23_45_B1_T2:
      - 3520_2_12_2_RNA_45_5_K562_SuRE23_TFrep1_PCRrep2_pgcDNA_adapter_2_150604_hg_ACTTGAA_L002_R1_001.fastq.gz

# plDNA Section.
plDNA:
  # Path to directory containing plDNA fastq files.
  FASTQ_DIR:
  # Path to sub-directory within 'OUTDIR' for plDNA related output
  OUTDIR:
  # Name of samples (used to label data files and data columns) with a list of fastq filenames
  SAMPLES:
